<?php
echo $t = time();
echo $currentdatetime = date("Y-m-d H:i", $t);
Mage::getModel('catdeals/observer')->setStatus();
$catdealsModel = Mage::getModel('catdeals/catdeals')->getCollection()->addFieldToFilter('deal_type', 1)->addFieldToFilter('status', 1)->getData();
foreach ($catdealsModel as $catdeal):
    $date = explode("/", $catdeal['date_to']);
    $time = explode(",", $catdeal['time_to']);
    $dealtime = $date[1] . '-' . $date[0] . '-' . $date[2] . ' ' . $time[0] . ':' . $time[1] . ':' . $time[2];
    $dealseconds = strtotime($dealtime) - time();
    ?>
    <a href="<?php echo Mage::helper('catdeals')->getUrl($catdeal['type_id']); ?>">
        <img width="100" height="100" src="<?php echo Mage::getBaseUrl('media'); ?>deals/category/<?php echo $catdeal['banner_file']; ?>">
    </a>
    <script>
        new Countdown({
            time: "<?php echo $dealseconds; ?>",
            width: 300,
            height: 60,
            rangeHi: "day",
            style: "flip"
        });
    </script>
    <?php
endforeach;
?>
