<?php
Mage::getModel('prdctdeals/observer')->setStatus();
$prdctdealsModel = Mage::getModel('prdctdeals/prdctdeals')->getCollection()->addFieldToFilter('deal_type', 2)->addFieldToFilter('status', 1)->getData();
foreach ($prdctdealsModel as $prdctdeal):   
    ?>
    <?php
    $date = explode("/", $prdctdeal['date_to']);
    $time = explode(",", $prdctdeal['time_to']);
    $dealtime = $date[1] . '-' . $date[0] . '-' . $date[2] . ' ' . $time[0] . ':' . $time[1] . ':' . $time[2];
    $dealseconds = strtotime($dealtime) - time();
    ?>
    <a href="<?php echo Mage::helper('prdctdeals')->getUrl($prdctdeal['type_id']); ?>">
        <img width="100" height="100" src="<?php echo Mage::getBaseUrl('media'); ?>deals/products/<?php echo $prdctdeal['banner_file']; ?>">
    </a>
    <script>
        new Countdown({
            time: "<?php echo $dealseconds; ?>",
            width: 300,
            height: 60,
            rangeHi: "day",
            style: "flip"	// <- no comma on last item!
        });
    </script> 
    <?php
endforeach;
?>